# Goal
string  work_type       # "PRODUCE" / "RECYCLE"
int32   product_id      # 만들거나 분해할 product_id (예: 13, 81)

---
# Feedback
string status           # "PROCESSING" / "PRODUCING" / "RECYCLING"

---
# Result
bool    success
string  fail_reason
